import type { DeltaDashCardDefinition } from './card-types';

// Source: docs/deltadash-card-abstraction.md — rulesRevision: "4.0-beta-user-revised"
// To update: re-read the markdown, find the card by slug, update conditions/effects/count/notes.

export const playableCardCatalog: DeltaDashCardDefinition[] = [
  // ── Prototype bridge cards (map current four actions) ──────────────────────
  {
    id: 'prototype.steady',
    slug: 'prototype-steady',
    name: { zh: '稳定推进', en: 'Steady' },
    summary: { zh: '+1.5s，+1 电量，按胎种约 -4% 至 -9% 轮胎。黄旗/限速下 +1.0s。', en: '+1.5s, +1 energy, about -4% to -9% tire by compound. +1.0s under yellow/speed cap.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 3,
    count: '∞',
    tags: ['timeDelta', 'energy', 'tire'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [
      { type: 'modify_time_delta', amount: 1.5, yellowAmount: 1 },
      { type: 'modify_energy', amount: 1, min: 0, max: 6 },
      { type: 'modify_tire', amount: -6, min: 0 },
    ],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'steady',
  },
  {
    id: 'prototype.push',
    slug: 'prototype-push',
    name: { zh: '强推', en: 'Push' },
    summary: { zh: '+2.5s，-2 电量，轮胎磨损约为稳定推进的 1.35 倍，增加事故风险。', en: '+2.5s, -2 energy, about 1.35× steady tyre wear, higher incident risk.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 5,
    count: '∞',
    tags: ['timeDelta', 'energy', 'tire', 'risk'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'min_energy', value: 2 }, { type: 'flag_not', value: 'yellow' }],
    effects: [
      { type: 'modify_time_delta', amount: 2.5 },
      { type: 'modify_energy', amount: -2, min: 0 },
      { type: 'modify_tire', amount: -9, min: 0 },
    ],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'push',
  },
  {
    id: 'prototype.defend',
    slug: 'prototype-defend',
    name: { zh: '防守', en: 'Defend' },
    summary: { zh: '+1.0s，保守通过本回合。', en: '+1.0s with safer race posture.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 'X',
    count: '∞',
    tags: ['timeDelta', 'defense'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'modify_time_delta', amount: 1 }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'defend',
  },
  {
    id: 'prototype.recover',
    slug: 'prototype-recover',
    name: { zh: '回收', en: 'Recover' },
    summary: { zh: '+0.5s，+2 电量，最多 +0.6% 轮胎冷却收益。', en: '+0.5s, +2 energy, up to +0.6% tyre cooling benefit.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 1,
    count: '∞',
    tags: ['timeDelta', 'energy', 'tire', 'recovery'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [
      { type: 'modify_time_delta', amount: 0.5 },
      { type: 'modify_energy', amount: 2, min: 0, max: 6 },
      { type: 'modify_tire', amount: 3, min: 0, max: 100 },
    ],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'recover',
  },

  // ── Action cards ───────────────────────────────────────────────────────────
  {
    id: 'action.attack',
    slug: 'attack',
    name: { zh: '攻', en: 'Attack' },
    summary: { zh: '核心进攻行动牌，优先级 5。', en: 'Core offensive action card, priority 5.' },
    category: 'action',
    timing: ['planning'],
    priority: 5,
    count: 'Variable, 6-18',
    tags: ['attack', 'timeDelta'],
    targeting: { kind: 'opponent', range: { minTimeGap: 0, maxTimeGap: 1, inFrontOnly: true } },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#攻-attack',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '近距离目标受到 -1.0s 时间差压制。', en: 'Applies -1.0s time-delta pressure to a close target.' }],
    actionBridge: 'push',
  },
  {
    id: 'action.defend',
    slug: 'defend',
    name: { zh: '防', en: 'Defend' },
    summary: { zh: '响应型防御牌，优先级 X。', en: 'Reactive defense card, priority X.' },
    category: 'response',
    timing: ['response'],
    priority: 'X',
    count: 'Variable, 6-12',
    tags: ['defense', 'response'],
    targeting: { kind: 'none' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#防-defend',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '使以自己为目标的攻牌失效。', en: 'Expires Attack cards targeting this car.' }],
  },
  {
    id: 'action.release',
    slug: 'release',
    name: { zh: '释放', en: 'Release' },
    summary: { zh: '用一张牌增加本回合能量释放，不超过 4.0MJ 上限。', en: 'Use one card to boost energy release this turn, capped at 4.0MJ.' },
    category: 'action',
    timing: ['planning'],
    priority: 3,
    count: 'Variable, 8-10',
    tags: ['energy', 'release'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'min_energy', value: 1 }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#释放-release--discharge',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '能量硬上限 4.0MJ，不可超支。', en: 'Hard energy cap is 4.0MJ; cannot exceed.' }],
  },
  {
    id: 'action.burn-tires',
    slug: 'burn-tires',
    name: { zh: '烧胎', en: 'Burn Tires' },
    summary: { zh: '甩过 1.5s 后，目标轮胎衰减加倍。', en: 'After passing within 1.5s, target tire degradation doubles.' },
    category: 'action',
    timing: ['planning'],
    priority: 3,
    count: '6',
    tags: ['tire', 'attack', 'proximity'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#烧胎-burn-tires',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '1.5 秒内目标轮胎衰减加倍。', en: 'Doubles target tire degradation within 1.5s.' }],
    actionBridge: 'push',
  },
  {
    id: 'action.protect-tires',
    slug: 'protect-tires',
    name: { zh: '保胎', en: 'Protect Tires' },
    summary: { zh: '后退 1.5s，本回合轮胎衰减不计。', en: 'Move back 1.5s; tire wear does not count this round.' },
    category: 'action',
    timing: ['planning'],
    priority: 1,
    count: '6',
    tags: ['tire', 'defense', 'position'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#保胎-protect-tires',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '后退 1.5 秒，本回合轮胎衰减不计。', en: 'Move back 1.5s; tire wear does not count this round.' }],
  },
  {
    id: 'action.recycle',
    slug: 'recycle',
    name: { zh: '回收', en: 'Recycle' },
    summary: { zh: '每张牌立即换取 1MJ，但下一回合不能普通释放。', en: 'Each card immediately exchanges for 1MJ; no normal release next round.' },
    category: 'action',
    timing: ['planning'],
    priority: 1,
    count: 'Variable, 6-10',
    tags: ['energy', 'recovery', 'hand'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'modify_energy', amount: 1, min: 0, max: 4 }, { type: 'set_round_modifier', modifier: 'no-normal-release-next-round' }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#回收-recycle--recover',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '立即获得 1MJ；下一回合没有普通释放。', en: 'Gain 1MJ immediately; no normal release next round.' }],
  },

  // ── Tactic cards ───────────────────────────────────────────────────────────
  {
    id: 'tactic.slaughter-all',
    slug: 'slaughter-all',
    name: { zh: '大杀四方', en: 'Slaughter All Sides' },
    summary: { zh: '消耗全部资源，对所有外部目标先手打击，无法防守。', en: 'Consume all resources; first strike all external targets; cannot be defended.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 6,
    count: '4',
    tags: ['attack', 'mass', 'unblockable'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'min_energy', value: 1 }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#大杀四方-slaughter-all-sides',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '消耗自身全部资源，按当前能量向前推进，并对经过目标造成专注损失。', en: 'Consumes all own resources, advances by current energy, and damages targets passed.' }],
  },
  {
    id: 'tactic.roundabout-rescue',
    slug: 'roundabout-rescue',
    name: { zh: '曲线救国', en: 'Roundabout Rescue' },
    summary: { zh: '由"攻"触发，后退 2s 并推开途中所有车手。', en: 'Triggered by Attack; fall back 2s and push back all drivers in the way.' },
    category: 'tactic',
    timing: ['response'],
    priority: 'X',
    count: '4',
    tags: ['position', 'response', 'combo'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#曲线救国-roundabout-rescue',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '后退 2 秒。', en: 'Fall back 2 seconds.' }],
  },
  {
    id: 'tactic.first-move-seize',
    slug: 'first-move-seize',
    name: { zh: '先手夺阵', en: 'First-Move Seize Position' },
    summary: { zh: '交换己方与对方的位置或牌。', en: 'Swap your position or card with an opponent.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['position', 'initiative'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#先手夺阵-first-move-seize-position',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '抓取任意一张牌。', en: 'Draw one card of any kind.' }],
  },
  {
    id: 'tactic.mgu-h-recovery',
    slug: 'mgu-h-recovery',
    name: { zh: '热能回收', en: 'MGU-H Recovery' },
    summary: { zh: '弃置 X 张牌，回收 X 点电量。', en: 'Discard X cards and recover X energy.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['energy', 'hand', 'recovery'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'has_hand_cards' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction-v3-implemented.md#热能回收-mgu-h-recovery',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '按当前手牌数回收 1-4 点电量。', en: 'Recover 1-4 energy from current hand count.' }],
  },
  {
    id: 'tactic.fishermans-profit',
    slug: 'fishermans-profit',
    name: { zh: '渔翁得利', en: "Fisherman's Profit" },
    summary: { zh: '3 方以上对抗时，交换自己与另一方的位置；若攻方有剩余能量则减 1MJ。', en: 'When 3+ parties clash, swap your position with another; if attacker has energy, decrease 1MJ.' },
    category: 'tactic',
    timing: ['response'],
    priority: 4,
    count: '4',
    tags: ['position', 'opportunistic', 'response'],
    targeting: { kind: 'opponent' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction-v3-implemented.md#渔翁得利-fishermans-profit',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '自己消耗 1 点电量，并与目标交换时间差位置。', en: 'You spend 1 energy and swap time-delta position with the target.' }],
  },
  {
    id: 'tactic.steadfast-lion',
    slug: 'steadfast-lion',
    name: { zh: '死守狮防', en: 'Steadfast Lion Defense' },
    summary: { zh: '免疫攻牌和任何形式的超车；可长期留在部署区，但每回合取消普通收获。', en: 'Immune to Attack and any passing; can stay deployed indefinitely but voids normal harvest each round.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 'X',
    count: '4',
    tags: ['defense', 'persistent', 'deploy-zone'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'set_round_modifier', modifier: 'steadfast-defense' }, { type: 'set_round_modifier', modifier: 'position-lock' }],
    onFailedConditions: 'stay-deployed',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#死守狮防-steadfast-lion-defense',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '设置防御姿态修正器。', en: 'Sets defensive posture modifier.' }],
  },
  {
    id: 'tactic.cant-hear',
    slug: 'cant-hear',
    name: { zh: '听不清楚', en: "Can't Hear Clearly" },
    summary: { zh: '可由任意战术牌触发，使该战术牌无效。', en: 'Can be triggered by any tactic card; makes that tactic card invalid.' },
    category: 'response',
    timing: ['response'],
    priority: 'X',
    count: '4',
    tags: ['silence', 'response', 'tactic'],
    targeting: { kind: 'opponent' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#听不清楚-cant-hear-clearly',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '使目标战术牌无效。', en: 'Counters the target tactic card.' }],
  },
  {
    id: 'tactic.little-tune-power',
    slug: 'little-tune-power',
    name: { zh: '小曲之力', en: 'Power of the Little Tune' },
    summary: { zh: '专注 +[骰子点数]，上限 4。', en: 'Focus +[dice result], capped at 4.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['focus', 'boost'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#小曲之力-power-of-the-little-tune',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '按确定性调值获得 1-4 点专注，上限 4。', en: 'Gain 1-4 focus from deterministic tune value, capped at 4.' }],
  },
  {
    id: 'tactic.rampaging-invasion',
    slug: 'rampaging-invasion',
    name: { zh: '狂降犯境', en: 'Rampaging Invasion' },
    summary: { zh: '除自己外所有人必须打出防，或防御被压制。', en: 'All opponents must play Defend, or defense is suppressed.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 6,
    count: '4',
    tags: ['mass', 'suppression', 'attack'],
    targeting: { kind: 'all-opponents' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#狂降犯境-rampaging-invasion',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '未回应的目标减少 2 点专注。', en: 'Targets that do not answer lose 2 focus.' }],
  },
  {
    id: 'tactic.plan-changed',
    slug: 'plan-changed',
    name: { zh: '计划有变', en: 'Plan Changed' },
    summary: { zh: '弃置 X 张手牌，补充对应类型的 X 张牌。', en: 'Discard X hand cards and replenish X cards of the corresponding type.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['hand', 'management'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'implemented',
    sourceRef: 'docs/deltadash-card-abstraction.md#计划有变-plan-changed',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '将 X 张手牌替换为同类别新牌。', en: 'Exchange X hand cards into new cards of the same kind.' }],
  },
];

export function getCardDefinitionById(id: string): DeltaDashCardDefinition | null {
  return playableCardCatalog.find((card) => card.id === id) ?? null;
}

export function getImplementedCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'implemented' && card.category !== 'prototype');
}

export function getRuntimePlayableCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'implemented' && card.category !== 'prototype');
}

export function getProvisionalCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'provisional');
}

export function getDocumentedOnlyCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'documented-only');
}
