import type { DeltaDashCardDefinition } from './card-types';

// Source: docs/deltadash-card-abstraction.md — rulesRevision: "4.0-beta-user-revised"
// To update: re-read the markdown, find the card by slug, update conditions/effects/count/notes.

export const playableCardCatalog: DeltaDashCardDefinition[] = [
  // ── Prototype bridge cards (map current four actions) ──────────────────────
  {
    id: 'prototype.steady',
    slug: 'prototype-steady',
    name: { zh: '稳定推进', en: 'Steady' },
    summary: { zh: '+3 进度，+1 电量，-1 轮胎。黄旗/限速下 +2。', en: '+3 progress, +1 energy, -1 tire. +2 under yellow/speed cap.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 3,
    count: '∞',
    tags: ['progress', 'energy', 'tire'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [
      { type: 'modify_progress', amount: 3, yellowAmount: 2 },
      { type: 'modify_energy', amount: 1, min: 0, max: 6 },
      { type: 'modify_tire', amount: -1, min: 0 },
    ],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'steady',
  },
  {
    id: 'prototype.push',
    slug: 'prototype-push',
    name: { zh: '强推', en: 'Push' },
    summary: { zh: '+5 进度，-2 电量，-2 轮胎，增加事故风险。', en: '+5 progress, -2 energy, -2 tire, higher incident risk.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 5,
    count: '∞',
    tags: ['progress', 'energy', 'tire', 'risk'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'min_energy', value: 2 }, { type: 'flag_not', value: 'yellow' }],
    effects: [
      { type: 'modify_progress', amount: 5 },
      { type: 'modify_energy', amount: -2, min: 0 },
      { type: 'modify_tire', amount: -2, min: 0 },
    ],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'push',
  },
  {
    id: 'prototype.defend',
    slug: 'prototype-defend',
    name: { zh: '防守', en: 'Defend' },
    summary: { zh: '+2 进度，保守通过本回合。', en: '+2 progress with safer race posture.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 'X',
    count: '∞',
    tags: ['progress', 'defense'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'modify_progress', amount: 2 }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'defend',
  },
  {
    id: 'prototype.recover',
    slug: 'prototype-recover',
    name: { zh: '回收', en: 'Recover' },
    summary: { zh: '+1 进度，+2 电量，+1 轮胎。', en: '+1 progress, +2 energy, +1 tire.' },
    category: 'prototype',
    timing: ['planning'],
    priority: 1,
    count: '∞',
    tags: ['progress', 'energy', 'tire', 'recovery'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [
      { type: 'modify_progress', amount: 1 },
      { type: 'modify_energy', amount: 2, min: 0, max: 6 },
      { type: 'modify_tire', amount: 1, min: 0, max: 6 },
    ],
    onFailedConditions: 'no-effect',
    implementationStatus: 'implemented',
    sourceRef: 'prototype',
    rulesRevision: '4.0-beta-user-revised',
    actionBridge: 'recover',
  },

  // ── Action cards ───────────────────────────────────────────────────────────
  {
    id: 'action.attack',
    slug: 'attack',
    name: { zh: '攻', en: 'Attack' },
    summary: { zh: '核心进攻行动牌，优先级 5。', en: 'Core offensive action card, priority 5.' },
    category: 'action',
    timing: ['planning'],
    priority: 5,
    count: 'Variable, 6-18',
    tags: ['attack', 'progress'],
    targeting: { kind: 'opponent' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Full attack rule text partially illegible; targeting semantics TBD.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#攻-attack',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'action.defend',
    slug: 'defend',
    name: { zh: '防', en: 'Defend' },
    summary: { zh: '响应型防御牌，优先级 X。', en: 'Reactive defense card, priority X.' },
    category: 'response',
    timing: ['response'],
    priority: 'X',
    count: 'Variable, 6-12',
    tags: ['defense', 'response'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Full defense rule text partially illegible.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#防-defend',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'action.release',
    slug: 'release',
    name: { zh: '释放', en: 'Release' },
    summary: { zh: '用一张牌增加本回合能量释放，不超过 4.0MJ 上限。', en: 'Use one card to boost energy release this turn, capped at 4.0MJ.' },
    category: 'action',
    timing: ['planning'],
    priority: 3,
    count: 'Variable, 8-10',
    tags: ['energy', 'release'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'min_energy', value: 1 }],
    effects: [{ type: 'modify_energy', amount: 1, min: 0, max: 4 }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'provisional',
    sourceRef: 'docs/deltadash-card-abstraction.md#释放-release--discharge',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '能量硬上限 4.0MJ，不可超支。', en: 'Hard energy cap is 4.0MJ; cannot exceed.' }],
  },
  {
    id: 'action.burn-tires',
    slug: 'burn-tires',
    name: { zh: '烧胎', en: 'Burn Tires' },
    summary: { zh: '甩过 1.5s 后，目标轮胎衰减加倍。', en: 'After passing within 1.5s, target tire degradation doubles.' },
    category: 'action',
    timing: ['planning'],
    priority: 3,
    count: '6',
    tags: ['tire', 'attack', 'proximity'],
    targeting: { kind: 'opponent' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Requires 1.5s proximity predicate; position model not yet implemented.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#烧胎-burn-tires',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'action.protect-tires',
    slug: 'protect-tires',
    name: { zh: '保胎', en: 'Protect Tires' },
    summary: { zh: '后退 1.5s，本回合轮胎衰减不计。', en: 'Move back 1.5s; tire wear does not count this round.' },
    category: 'action',
    timing: ['planning'],
    priority: 1,
    count: '6',
    tags: ['tire', 'defense', 'position'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'set_round_modifier', modifier: 'no-tire-wear' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'provisional',
    sourceRef: 'docs/deltadash-card-abstraction.md#保胎-protect-tires',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '位置后退惩罚暂时省略，等位置模型完善后补充。', en: 'Position penalty is provisional until the position model is implemented.' }],
  },
  {
    id: 'action.recycle',
    slug: 'recycle',
    name: { zh: '回收', en: 'Recycle' },
    summary: { zh: '每张牌立即换取 1MJ，但下一回合不能普通释放。', en: 'Each card immediately exchanges for 1MJ; no normal release next round.' },
    category: 'action',
    timing: ['planning'],
    priority: 1,
    count: 'Variable, 6-10',
    tags: ['energy', 'recovery', 'hand'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'modify_energy', amount: 1, min: 0, max: 4 }, { type: 'set_round_modifier', modifier: 'no-normal-release-next-round' }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'provisional',
    sourceRef: 'docs/deltadash-card-abstraction.md#回收-recycle--recover',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: '超车模式下可叠加使用；其他情况每回合只能用一张。', en: 'Can be stacked in Overtake mode; otherwise one per round.' }],
  },

  // ── Tactic cards ───────────────────────────────────────────────────────────
  {
    id: 'tactic.slaughter-all',
    slug: 'slaughter-all',
    name: { zh: '大杀四方', en: 'Slaughter All Sides' },
    summary: { zh: '消耗全部资源，对所有外部目标先手打击，无法防守。', en: 'Consume all resources; first strike all external targets; cannot be defended.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 6,
    count: '4',
    tags: ['attack', 'mass', 'unblockable'],
    targeting: { kind: 'all-opponents' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Full resource-consume and unblockable semantics TBD.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#大杀四方-slaughter-all-sides',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.roundabout-rescue',
    slug: 'roundabout-rescue',
    name: { zh: '曲线救国', en: 'Roundabout Rescue' },
    summary: { zh: '由"攻"触发，后退 2s 并推开途中所有车手。', en: 'Triggered by Attack; fall back 2s and push back all drivers in the way.' },
    category: 'tactic',
    timing: ['response'],
    priority: 'X',
    count: '4',
    tags: ['position', 'response', 'combo'],
    targeting: { kind: 'none' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Requires position model and response-window trigger.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#曲线救国-roundabout-rescue',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.first-move-seize',
    slug: 'first-move-seize',
    name: { zh: '先手夺阵', en: 'First-Move Seize Position' },
    summary: { zh: '交换己方与对方的位置或牌。', en: 'Swap your position or card with an opponent.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['position', 'initiative'],
    targeting: { kind: 'opponent' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Swap semantics partially unclear.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#先手夺阵-first-move-seize-position',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.em-recovery',
    slug: 'em-recovery',
    name: { zh: '电磁回收', en: 'Electromagnetic Recovery' },
    summary: { zh: '弃置 X 张牌，回收 X 点电量。', en: 'Discard X cards and recover X energy.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['energy', 'hand', 'recovery'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }],
    effects: [{ type: 'modify_energy', amount: 1, min: 0, max: 4 }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'provisional',
    sourceRef: 'docs/deltadash-card-abstraction.md#电磁回收-electromagnetic-recovery',
    rulesRevision: '4.0-beta-user-revised',
    interpretationNotes: [{ zh: 'X 值暂时固定为 1；变量 X 等手牌系统完善后再扩展。', en: 'X is fixed at 1 for now; variable X will be expanded when the hand system is complete.' }],
  },
  {
    id: 'tactic.fishermans-profit',
    slug: 'fishermans-profit',
    name: { zh: '渔翁得利', en: "Fisherman's Profit" },
    summary: { zh: '3 方以上对抗时，交换自己与另一方的位置；若攻方有剩余能量则减 1MJ。', en: 'When 3+ parties clash, swap your position with another; if attacker has energy, decrease 1MJ.' },
    category: 'tactic',
    timing: ['response'],
    priority: 4,
    count: '4',
    tags: ['position', 'opportunistic', 'response'],
    targeting: { kind: 'none' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Requires 3-party board state predicate and position swap.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'no-effect',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#渔翁得利-fishermans-profit',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.steadfast-lion',
    slug: 'steadfast-lion',
    name: { zh: '死守狮防', en: 'Steadfast Lion Defense' },
    summary: { zh: '免疫攻牌和任何形式的超车；可长期留在部署区，但每回合取消普通收获。', en: 'Immune to Attack and any passing; can stay deployed indefinitely but voids normal harvest each round.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 'X',
    count: '4',
    tags: ['defense', 'persistent', 'deploy-zone'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Persistent deploy-zone and harvest-void mechanics TBD.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'stay-deployed',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#死守狮防-steadfast-lion-defense',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.cant-hear',
    slug: 'cant-hear',
    name: { zh: '听不清楚', en: "Can't Hear Clearly" },
    summary: { zh: '可由任意战术牌触发，使该战术牌无效。', en: 'Can be triggered by any tactic card; makes that tactic card invalid.' },
    category: 'response',
    timing: ['response'],
    priority: 'X',
    count: '4',
    tags: ['silence', 'response', 'tactic'],
    targeting: { kind: 'none' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Requires response-window and tactic-card targeting.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#听不清楚-cant-hear-clearly',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.little-tune-power',
    slug: 'little-tune-power',
    name: { zh: '小曲之力', en: 'Power of the Little Tune' },
    summary: { zh: '专注 +[骰子点数]，上限 4。', en: 'Focus +[dice result], capped at 4.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['focus', 'boost'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Focus resource not yet modeled in match state.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#小曲之力-power-of-the-little-tune',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.rampaging-invasion',
    slug: 'rampaging-invasion',
    name: { zh: '狂降犯境', en: 'Rampaging Invasion' },
    summary: { zh: '除自己外所有人必须打出防，或防御被压制。', en: 'All opponents must play Defend, or defense is suppressed.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 6,
    count: '4',
    tags: ['mass', 'suppression', 'attack'],
    targeting: { kind: 'all-opponents' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Force-defend semantics TBD.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#狂降犯境-rampaging-invasion',
    rulesRevision: '4.0-beta-user-revised',
  },
  {
    id: 'tactic.plan-changed',
    slug: 'plan-changed',
    name: { zh: '计划有变', en: 'Plan Changed' },
    summary: { zh: '弃置 X 张手牌，补充对应类型的 X 张牌。', en: 'Discard X hand cards and replenish X cards of the corresponding type.' },
    category: 'tactic',
    timing: ['planning'],
    priority: 2,
    count: '4',
    tags: ['hand', 'management'],
    targeting: { kind: 'self' },
    conditions: [{ type: 'not_retired' }, { type: 'documented-only', reason: 'Hand/deck system not yet implemented.' }],
    effects: [{ type: 'no_effect' }],
    onFailedConditions: 'return-to-hand',
    implementationStatus: 'documented-only',
    sourceRef: 'docs/deltadash-card-abstraction.md#计划有变-plan-changed',
    rulesRevision: '4.0-beta-user-revised',
  },
];

export function getCardDefinitionById(id: string): DeltaDashCardDefinition | null {
  return playableCardCatalog.find((card) => card.id === id) ?? null;
}

export function getImplementedCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'implemented');
}

export function getProvisionalCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'provisional');
}

export function getDocumentedOnlyCards(): DeltaDashCardDefinition[] {
  return playableCardCatalog.filter((card) => card.implementationStatus === 'documented-only');
}
